export const AI_TIPS = {
  hyped: [
    "Peak energy detected! Dive straight into complex Math & Physics problem sets.",
    "Your focus is primed. Tackle your hardest coding or architectural task now.",
    "High dopamine window! Execute 90 minutes of uninterrupted Deep Study.",
    "Ideal moment for heavy cognitive work: Tackle Advanced Algebra now.",
    "Capitalize on this surge: Solve past exam papers or complex theory.",
    "Maximum mental bandwidth available. Tackle your pending project milestones.",
    "Energy peak aligned! Switch to challenging problem-solving immediately.",
    "Prime focus window! Excellent time for intense memorization and deep synthesis.",
    "Unstoppable momentum detected: Push through high-priority tasks now.",
    "System primed for heavy load: Execute complex analytical tasks.",
    "Peak focus unlocked! Tackle 2-3 intensive study blocks back-to-back.",
    "High alertness detected: Solve complex system design and algorithm challenges.",
    "Optimal cognitive state! Draft critical project documentations or write code.",
    "Focus momentum at 100%: Review challenging STEM modules right now.",
    "High energy window! Tackle tough calculus or physics derivations.",
    "Prime productivity surge: Clear your most demanding schedule items.",
    "High focus online: Tackle competitive programming or logic puzzles.",
    "Maximum throughput mode: Work through 2 hours of deep work tasks.",
    "Mental clarity peaked: Tackle difficult language grammar or essay drafts.",
    "Unstoppable drive: Execute sprint-based deep study sessions now.",
    "High alertness: Focus on complex mechanics, physics, or data structures.",
    "Brain operating at maximum speed: Solve high-difficulty practice tests.",
    "Optimal window for deep learning: Master new complex concepts today.",
    "Peak focus: Engage in intensive research and structured note synthesis.",
    "High mental stamina: Tackle multi-step project tasks immediately.",
    "Power window active: Complete your highest value study objectives.",
    "Optimal cognitive bandwidth: Conquer advanced mathematical proofs.",
    "High focus state: Solve 15-20 complex application problems.",
    "Mental energy high: Review difficult chemistry formulas and reactions.",
    "Prime state: Push through long-form reading and critical synthesis.",
    "High productivity surge: Clear deep study backlogs immediately.",
    "Optimal alertness: Build and test complex code modules now.",
    "Peak state: Conquer multi-subject study blocks efficiently.",
    "High focus: Solve full-length practice sections without breaks.",
    "Mental clarity 100%: Execute strategic project planning and execution.",
    "Prime cognitive state: Solve high-level physics or engineering tasks.",
    "Energy peak: Master complex algorithmic logic and data flows.",
    "High focus window: Write comprehensive technical reviews.",
    "Maximum drive: Tackle difficult quantitative reasoning sets.",
    "Optimal focus: Execute heavy memorization and active recall.",
    "Peak performance: Solve advanced logic and calculus sets.",
    "High focus surge: Deep dive into full-chapter study modules.",
    "Maximum alertness: Work through challenging project sprints.",
    "Prime focus: Tackle advanced data analysis and model building.",
    "High energy: Execute intensive flashcard active recall sessions.",
    "Optimal cognitive surge: Solve timed practice exam sections.",
    "Peak focus: Master advanced organic chemistry or biology pathways.",
    "High alertness: Complete critical coding architecture tasks.",
    "Unstoppable momentum: Conquer your longest study block today.",
    "Prime state active: Tackle top-priority exam preparation items.",
    "High focus: Execute deep technical problem sets with high accuracy.",
    "Peak alertness: Review and solve challenging olympiad-style questions.",
    "Maximum throughput: Complete full-length mock exams efficiently.",
    "Optimal drive: Master complex system physics and thermodynamics.",
    "High energy: Tackle multi-variable calculus problem sets.",
    "Prime focus: Analyze and synthesize complex research papers.",
    "Peak mental state: Write and optimize complex algorithms.",
    "High alertness: Execute 90-minute hyper-focused study sprints.",
    "Optimal momentum: Solve top-tier quantitative practice exams.",
    "High cognitive state: Conquer challenging hardware/software labs.",
    "Peak focus surge: Master difficult foreign language grammar modules.",
    "Unstoppable focus: Complete high-demand engineering assignments.",
    "Prime energy window: Solve complex probability and statistics sets.",
    "High alertness: Execute deep focus writing and essay structuring.",
    "Maximum capacity: Tackle full-stack application development sprints.",
    "Optimal focus: Review comprehensive medical or biological diagrams.",
    "Peak mental surge: Solve 25+ challenging application questions.",
    "High focus mode: Master difficult financial modeling or macroeconomics.",
    "Prime state: Execute structured Pomodoro hyper-sprints now.",
    "High alertness: Deep dive into organic chemistry mechanisms.",
    "Peak focus: Master complex signal processing or linear algebra.",
    "Optimal energy: Complete intense project review cycles.",
    "High drive: Solve full practice test modules with zero distraction.",
    "Unstoppable state: Complete top 3 critical daily milestones now.",
    "Prime focus: Tackle challenging logic gates and digital circuits.",
    "High mental clarity: Master full history or literature synthesis.",
    "Peak alertness: Solve advanced geometry and trigonometry sets.",
    "Maximum energy: Build full prototype models or code scripts.",
    "Optimal state: Review and memorize 100+ active recall cards.",
    "High focus surge: Conquer tough technical interview questions.",
    "Prime mental window: Solve advanced microeconomics problems.",
    "Peak performance: Complete full chapter summaries in detail.",
    "High alertness: Deep dive into computer network protocols.",
    "Optimal drive: Tackle intense data science and ML pipelines.",
    "Unstoppable momentum: Clear all pending high-priority study tasks.",
    "Prime energy: Master complex mechanics and kinematics equations.",
    "High focus: Solve advanced differential equations immediately.",
    "Peak state: Complete comprehensive full-stack code reviews.",
    "Maximum capacity: Execute 2 continuous deep work blocks.",
    "Optimal alertness: Master challenging structural analysis topics.",
    "High energy surge: Solve top-tier competitive math problems.",
    "Prime state: Tackle full essay drafts with high focus.",
    "Peak focus: Conquer tough molecular biology pathways.",
    "High drive: Solve multi-step physics circuit problems.",
    "Optimal cognitive state: Master complex database design schemas.",
    "Unstoppable energy: Complete full study guide reviews today.",
    "Prime focus: Execute 90-minute timed study sessions now.",
    "Peak mental performance: Master full-spectrum STEM problem sets.",
    "High alertness: Complete all core project objectives efficiently.",
    "Maximum focus: Tackle your most ambitious study goal right now!"
  ],
  fog: [
    "Brain fog detected. Switch to light 15-minute flashcard review.",
    "Cognitive load high. Organize your notes or tidy up your workspace.",
    "Lower focus detected. Review completed tasks or watch a brief video lecture.",
    "Brain fatigue active. Do light active recall instead of heavy problem solving.",
    "Foggy focus window. Listen to educational audio summaries at easy pace.",
    "Mental fatigue detected. Take a 10-minute breathwork session before resuming.",
    "Low cognitive energy. Sort schedule items and clear trivial study tasks.",
    "Brain operating slow. Switch from solving to reading summary sheets.",
    "Mental fog active. Do a quick 5-minute mind dump on paper.",
    "Low focus window. Review vocabulary or light definitions.",
    "Brain fatigue detected. Convert heavy text into simple bullet point notes.",
    "Cognitive battery low. Take 15 minutes to review previous correct answers.",
    "Foggy mind. Switch to low-stress administrative tasks or email organization.",
    "Low mental bandwidth. Listen to relaxing lo-fi music while tidying files.",
    "Brain fog active. Hydrate with water and do light stretch exercises.",
    "Focus compromised. Solve 3 easy practice warm-ups to rebuild momentum.",
    "Fatigue detected. Read 2 pages of summary notes without pressing for perfection.",
    "Low cognitive drive. Re-organize study folders and bookmark key pages.",
    "Brain fog window. Do a gentle 10-minute walk before trying heavy work.",
    "Mental overload. Switch to passive learning like instructional podcasts.",
    "Low focus state. Highlight key terms in your textbook without pressure.",
    "Foggy state. Clean your desk surface and reset your study environment.",
    "Cognitive pause required. Do 5 minutes of box breathing now.",
    "Brain fatigue active. Review formula sheets passively without solving.",
    "Low focus detected. Check off small 5-minute easy schedule items.",
    "Mental fog window. Watch a 10-minute visual breakdown of the topic.",
    "Low cognitive energy. Update your task tracker and mark done items.",
    "Brain fatigue active. Drink cold water and step away from screens briefly.",
    "Foggy focus state. Practice light active recall on easy concepts.",
    "Cognitive battery low. Do simple data entry or note formatting.",
    "Brain fog detected. Do 15 minutes of passive audio listening.",
    "Low focus state. Review flashcards you already know well for confidence.",
    "Mental fatigue active. Take a short 10-minute eye relaxation break.",
    "Foggy mind state. Re-read previous study summaries gently.",
    "Low energy window. Organize desktop files and clear clutter.",
    "Brain fog active. Sketch simple concept diagrams instead of writing text.",
    "Mental overload. Sip herbal tea and step outside for fresh air.",
    "Low focus detected. Review basic glossary definitions.",
    "Brain fatigue active. Listen to background ambient study audio.",
    "Foggy cognitive state. Do a quick 5-minute desk stretch routine.",
    "Low focus window. Check off simple administrative study tasks.",
    "Mental fog detected. Review light summary slides.",
    "Cognitive energy low. Do 10 minutes of guided mindfulness.",
    "Brain fatigue active. Convert complex notes into visual mind maps.",
    "Low mental bandwidth. Re-watch short tutorial clips.",
    "Foggy focus state. Take 10 deep breaths and drink water.",
    "Cognitive fatigue detected. Do easy flashcards only.",
    "Brain fog window. Organize physical notebooks and pens.",
    "Low focus state. Read introductory chapter overviews softly.",
    "Mental overload. Take a brief break from screens and glare.",
    "Foggy mind detected. Review simple formula reference cards.",
    "Low energy state. Clean up your digital browser tabs.",
    "Brain fatigue active. Listen to topic overviews on 1x speed.",
    "Cognitive battery low. Do light active recall for 10 minutes.",
    "Foggy state. Step away and wash your face with cold water.",
    "Low focus detected. Sort study notes chronologically.",
    "Brain fog window. Solve 2-3 basic introductory problems.",
    "Mental overload. Take a 15-minute power nap if possible.",
    "Low cognitive energy. Color-code your study schedule.",
    "Foggy mind active. Review basic concept bullet points.",
    "Brain fatigue detected. Do gentle neck and shoulder stretches.",
    "Low focus window. Listen to educational podcasts passively.",
    "Mental fog active. Clear out old physical study papers.",
    "Cognitive state low. Review easy definitions and terms.",
    "Brain fatigue detected. Drink a glass of water and rest eyes.",
    "Low focus state. Do 5 minutes of light habit tracking updates.",
    "Foggy focus state. Re-read highlight points from yesterday.",
    "Mental overload. Switch off intense notifications for 20 mins.",
    "Low energy window. Do simple copy-work or note transcription.",
    "Brain fog active. Take a 10-minute quiet mindfulness break.",
    "Cognitive fatigue low. Skim introductory lesson slides.",
    "Foggy mind state. Organize subject folders on Google Drive.",
    "Low focus detected. Watch 3-minute quick explainer shorts.",
    "Brain fatigue active. Do 10 minutes of light stretching.",
    "Mental fog window. Check off simple calendar reminders.",
    "Low cognitive drive. Review basic unit conversions and constants.",
    "Foggy state. Step into fresh air and stretch your legs.",
    "Brain fatigue active. Read casual articles related to your subject.",
    "Low focus window. Update your weekly study planner softly.",
    "Mental overload. Hydrate and sit quietly away from noise.",
    "Foggy mind detected. Review simple diagram labels.",
    "Low energy state. Skim table of contents for overview.",
    "Brain fatigue active. Do 10 minutes of passive listening.",
    "Cognitive battery low. Reset your study desk setup.",
    "Foggy focus state. Review basic vocabulary flashcards.",
    "Low focus detected. Solve 1-2 easy warm-up questions.",
    "Mental fog active. Take a 12-minute screen-free break.",
    "Low cognitive drive. Organize your study bookmarked links.",
    "Brain fatigue active. Do gentle posture alignment stretches.",
    "Foggy mind state. Read short summary paragraphs gently.",
    "Low focus window. Clear out unneeded email notifications.",
    "Mental overload. Sip water and relax shoulder tension.",
    "Cognitive energy low. Skim simple infographic overviews.",
    "Brain fatigue active. Review easy active recall questions.",
    "Foggy state. Take 5 deep breaths and stretch arms.",
    "Low focus detected. Organize your project resource links.",
    "Mental fog window. Read simple introduction sheets.",
    "Low cognitive drive. Do 10 minutes of low-stress review.",
    "Brain fatigue active. Take a well-deserved short rest now.",
    "Optimal adjustment: Keep tasks light and recover mental energy!"
  ],
  break: [
    "Need a Break active. Stand up, stretch, and grab a glass of water.",
    "Rest interval needed. Take a 15-minute screen-free walk.",
    "Recovery mode requested. Do 10 minutes of deep breathing and relaxation.",
    "Time to recharge! Step away from your desk for 15 minutes.",
    "Break recommended. Hydrate and do gentle neck stretches.",
    "Rest period active. Look away from screens at a distance for 5 minutes.",
    "Recharge interval: Step outside for fresh air and sunlight.",
    "Pause needed. Practice 10 minutes of guided meditation or quiet rest.",
    "Take a breather! Enjoy a warm cup of water or tea.",
    "Break time active. Do a 5-minute full body stretch routine.",
    "Recovery interval: Close your eyes and rest your mind for 10 mins.",
    "Rest recommended. Step away from study materials completely.",
    "Recharge state: Listen to relaxing music away from your screen.",
    "Break active! Walk around the room and stretch your legs.",
    "Pause needed: Hydrate with cold water and refresh your face.",
    "Time for a break! Step into a calm environment for 15 minutes.",
    "Rest interval: Do 5 minutes of shoulder and wrist stretches.",
    "Recharge active: Enjoy a light healthy snack and hydrate.",
    "Take a breather! Practice slow deep diaphragm breathing.",
    "Break window open: Give your eyes a complete rest from digital screens.",
    "Recovery mode: Sit comfortably and relax all muscle tension.",
    "Pause recommended: Step outside to catch fresh breeze.",
    "Rest active: Do gentle lower back and leg stretches.",
    "Recharge time: Step away from work and chat briefly with family.",
    "Break recommended: Rest quietly without checking notifications.",
    "Time to recharge: Sip water slowly and relax your shoulders.",
    "Rest interval active: Listen to calm ambient nature sounds.",
    "Pause needed: Do a 10-minute gentle walking break.",
    "Break active: Put down pens and screens for a complete reset.",
    "Recovery window: Close your eyes and practice box breathing.",
    "Rest recommended: Step away and stretch your neck and arms.",
    "Recharge mode: Enjoy fresh fruit and a glass of water.",
    "Take a break! Stand up and do 10 gentle arm swings.",
    "Pause interval: Look at distant outdoor scenery for 3 minutes.",
    "Break active: Disconnect from all study tabs for 15 mins.",
    "Recovery state: Sit in a comfortable chair and rest quietly.",
    "Rest recommended: Hydrate and do gentle spine twists.",
    "Time for a breather: Step into natural light for 10 minutes.",
    "Recharge active: Enjoy a relaxing cup of herbal tea.",
    "Break window: Do 5 minutes of slow mindfulness breathing.",
    "Pause needed: Step away from your desk and stretch thoroughly.",
    "Rest active: Give your brain a 15-minute full rest window.",
    "Recovery mode: Relax your jaw, shoulders, and eye muscles.",
    "Take a break! Do a quick 10-minute peaceful walk.",
    "Recharge interval: Sip cold water and rest screen-free.",
    "Break recommended: Practice 5 minutes of gentle body stretches.",
    "Pause interval: Close your eyes and listen to peaceful sounds.",
    "Rest state active: Step outside and enjoy fresh air.",
    "Time for a break: Step away from all study materials now.",
    "Recharge active: Enjoy a light snack and rest your eyes.",
    "Break window open: Stretch your legs and walk around.",
    "Pause needed: Relax in a quiet room for 10 minutes.",
    "Rest recommended: Do gentle wrist and finger stretches.",
    "Recovery state: Look out the window and relax visual focus.",
    "Take a breather! Hydrate with fresh water immediately.",
    "Recharge mode: Step away from all digital devices.",
    "Break active: Practice 10 deep belly breaths quietly.",
    "Pause interval: Do a 5-minute gentle neck release stretch.",
    "Rest recommended: Sit quietly and let your mind wander.",
    "Time to recharge: Take a 15-minute complete relaxation break.",
    "Break window: Step outside for sunlight and fresh air.",
    "Recovery active: Drink water and relax your facial muscles.",
    "Pause needed: Do gentle hamstring and calf stretches.",
    "Rest state: Close your eyes and take 10 slow breaths.",
    "Take a break! Enjoy a short screen-free quiet window.",
    "Recharge interval: Step away and refresh with cold water.",
    "Break recommended: Walk around and stretch your arms high.",
    "Pause interval: Relax quietly without any audio or video.",
    "Rest active: Give your mind full permission to rest now.",
    "Time for a breather: Do 5 minutes of gentle posture resets.",
    "Recharge mode: Hydrate and enjoy a brief quiet moment.",
    "Break window: Step away from study area for 15 minutes.",
    "Recovery active: Relax your shoulders down and breathe deep.",
    "Pause needed: Look at green plants or outdoor views.",
    "Rest recommended: Do a gentle 10-minute stretch break.",
    "Take a break! Sip herbal tea and relax your muscles.",
    "Recharge interval: Step into fresh air for 5 minutes.",
    "Break state active: Rest your eyes completely away from screens.",
    "Pause needed: Walk slowly around your room and relax.",
    "Rest recommended: Practice 5 minutes of gentle breathing.",
    "Time to recharge: Sit back, relax, and breathe deeply.",
    "Break window open: Disconnect from all task notifications.",
    "Recovery mode: Hydrate with water and stretch your back.",
    "Pause interval: Do gentle eye rotation exercises.",
    "Rest state active: Take a calm 15-minute rest window.",
    "Take a breather! Step outside and take 5 deep breaths.",
    "Recharge active: Enjoy a healthy light snack screen-free.",
    "Break recommended: Stand up, stretch, and relax completely.",
    "Pause needed: Sit in a quiet space and close your eyes.",
    "Rest interval: Give your hands and wrists a full break.",
    "Time for a break: Refresh your face with cool water.",
    "Recharge mode: Step away from your workspace entirely.",
    "Break window: Do 10 minutes of gentle yoga or stretches.",
    "Recovery state: Listen to calm soothing audio quietly.",
    "Pause needed: Walk around and stretch your spine gently.",
    "Rest recommended: Rest your mind and body screen-free.",
    "Take a break! Hydrate and enjoy a peaceful 15 minutes.",
    "Recharge active: Step outside for fresh outdoor air.",
    "Break window open: Relax completely before returning to work.",
    "Optimal recovery: Recharging now guarantees peak focus later!"
  ]
};